language: node_js
node_js: lts/*

cache:
  directories:
  - node_modules

install:
- npm install

script:
- npm test

after_success:
- openssl aes-256-cbc -K $encrypted_15c620f69909_key -iv $encrypted_15c620f69909_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
- git remote add deploy $SERVER_USERNAME@$SERVER_IP:$SERVER_APP_NAME
- git push deploy master

branches:
- master
